server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    table: schrma_version
    baseline-on-migrate: true
    out-of-order: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
